---
apt_pkgs:
  - fontconfig
  - gcc
  - git
  - gir1.2-secret-1
  - libcairo2-dev
  - make
  - maven
  - pkg-config
  - python3
  - python3-dev
  - python3-venv
  - python-is-python3
  - python3-pip
  - pythonpy
  - unzip
  - xclip
  - zsh

user: jack
