---
- hosts: local

  tasks:
    - name: install zsh
      apt:
        name:
          - zsh
          - fontconfig
          - git
        state: latest
      become: yes

    - name: Check for Powerline Fonts
      stat:
        path: ~/.local/share/fonts/PowerlineSymbols.otf
      register: pl_fonts_exists

    - name: Install Powerline Fonts
      shell: |
        wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
        wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
        mkdir -p  ~/.local/share/fonts/
        mkdir -p ~/.config/fontconfig/conf.d/
        mv PowerlineSymbols.otf ~/.local/share/fonts/
        fc-cache -vf ~/.local/share/fonts/
        mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
      when: not pl_fonts_exists.stat.exists

    - name: Check for Prezto
      stat:
        path: ~/.zprezto
      register: prezto_exists

    - name: install Prezto
      shell: |
        git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
        setopt EXTENDED_GLOB
        for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
          ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
        done
      args:
        executable: /bin/zsh
      when: not prezto_exists.stat.exists
