---
- hosts: local
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Packages
      apt:
        name: "{{ apt_pkgs }}"
        state: latest

    - name: Check for TFSwitch
      stat:
        path: /usr/local/bin/tfswitch
      register: tf_exists

    - name: Install TFSwitch
      shell: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
      when: not tf_exists.stat.exists

    - name: Create a src directory
      file:
        path: /mnt/c/src
        state: directory

    - name: soft link to /mnt/c/src
      file:
        src: /mnt/c/src
        dest: /home/{{ user }}/src
        owner: "{{ user }}"
        group: "{{ user }}"
        state: link

    - name: Create user path
      file:
        path: /home/{{ user }}/bin
        owner: "{{ user }}"
        group: "{{ user }}"
        state: directory
      when: user is defined

    - name: Download git-prompt
      get_url:
        url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
        dest: /home/{{ user }}/.git-prompt.sh
        mode: "0644"

    - name: Append to .bashrc
      blockinfile:
        path: /home/{{ user }}/.bashrc
        block: |
          # Git Prompt
          source ~/.git-prompt.sh
          PS1='$(__git_ps1 "(%s)")'$PS1
          # Git Helper Functions
          function gbclean() {
            local dest="${1:-develop}"
            git fetch --all --prune && git checkout ${dest} && git merge origin/${dest} && git branch --merged | egrep -v "(^\*|master|dev|${dest})" | xargs git branch -d && git checkout - > /dev/null 2>&1
          }
          # PATH
          export PATH=/home/{{ user }}/bin:$PATH
      when: user is defined

    - name: Append to .zshrc
      blockinfile:
        path: /home/{{ user }}/.zshrc
        block: |
          export PATH=/home/{{ user }}/bin:$PATH
      when: user is defined
