---
- hosts: local
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes
        
    - name: Install Azure CLI
      apt:
        name: azure-cli
        state: present

