---
- hosts: local
  become: yes
  become_user: root
  become_method: sudo

  tasks:

              - name: install Networking Packages
      yum:
        name: "{{ pkgs }}"
        state: latest
      vars:
        pkgs:
        - nmap

    - name: install vim
      yum:
        name: vim
        state: latest
